/**
 * Centralized content index — single source of truth for all published
 * clinic reviews, learn articles, and guides. All routes and server.js
 * require from here. No hardcoded clinic/article data in route files.
 * Last updated: 2026-06-08 — 11 clinics, 8 learn articles.
 * FIXED: NO DUPLICATE CLINICS DATA IN routes/clinics.js — THIS IS THE ONLY SOURCE.
 *
 * DIAGNOSTIC: startup check in server.js confirms clinic count at boot.
 */

// ── LEARN ARTICLES ────────────────────────────────────────────────────────────
const TOPICS = [
  {
    slug: 'what-is-trt',
    title: 'What is testosterone replacement therapy?',
    description: 'The science behind TRT: how it works, who it is for, and what the research says about long-term use.',
    level: 'Beginner',
    icon: '🧬',
  },
  {
    slug: 'trt-lab-values',
    title: 'Understanding your TRT lab values',
    description: 'Total T, free T, SHBG, estradiol, hematocrit — what each number means and what healthy ranges look like for men on TRT.',
    level: 'Intermediate',
    icon: '🧪',
  },
  {
    slug: 'trt-for-beginners',
    title: 'TRT for beginners: Your first 90 days',
    description: 'What to expect in your first three months on TRT: evaluation, dosing, monitoring, and realistic timeline for results.',
    level: 'Beginner',
    icon: '💉',
  },
  {
    slug: 'trt-benefits',
    title: 'Benefits of TRT: What the evidence actually shows',
    description: 'An honest look at what TRT reliably does — and what it does not. Sexual function, body composition, bone density, and more.',
    level: 'Intermediate',
    icon: '⚡',
  },
  {
    slug: 'trt-side-effects',
    title: 'TRT side effects and risks: What every candidate should know',
    description: 'Hematocrit, estradiol, fertility, prostate — understanding the real risk profile and what responsible monitoring looks like.',
    level: 'Intermediate',
    icon: '⚠️',
  },
  {
    slug: 'trt-cost',
    title: 'TRT cost: What you are actually paying for',
    description: 'A breakdown of where your money goes: medication, labs, consultations, and how to evaluate pricing transparency.',
    level: 'Beginner',
    icon: '💰',
  },
  {
    slug: 'trt-vs-natural',
    title: 'TRT vs Natural: What Actually Happens to Your Body When You Start',
    description: 'A factual breakdown of what changes in your endocrine system when you start TRT — HPG axis suppression, hematocrit, estrogen, DHT, body composition, and what happens when you stop. Includes comparison table and FAQ schema.',
    level: 'Intermediate',
    icon: '⚖️',
    tags: ['trt', 'hormones', 'health', 'natural-testosterone', 'body-effects'],
    author: 'TRT Compass Editorial',
    wordCount: 1220,
    faqs: [
      { q: 'Will I feel the effects immediately?', a: 'Most men notice improved energy and mood within 2–4 weeks. Full body composition and sexual function changes typically emerge over 3–6 months.' },
      { q: 'Does TRT cause prostate cancer?', a: 'No established causal link exists. However, TRT can accelerate existing prostate cancer, which is why baseline PSA and ongoing monitoring are standard.' },
      { q: 'Can I boost natural testosterone without TRT?', a: 'Yes. Sleep (8+ hours), resistance training (heavy compound lifts), adequate vitamin D, zinc, and magnesium, and body fat reduction below 20% all measurably raise natural testosterone in men with marginal levels.' },
      { q: 'Will TRT make me "shut down" permanently?', a: 'Not usually. Most men recover natural production within 3–12 months of stopping. Some require medical support (hCG or clomiphene) to restart the HPG axis.' }
    ]
  },
  {
    slug: 'how-long-does-trt-take-to-work',
    title: 'How Long Does TRT Take to Work? A Realistic Timeline',
    description: 'A data-backed week-by-week timeline for TRT results — what improves when, common protocol failure modes, and what to track in your first 12 months on therapy.',
    tags: ['trt', 'protocol', 'timeline', 'expectations', 'results'],
    author: 'TRT Compass Editorial',
    wordCount: 1250,
    faqs: [
      { q: 'I started TRT 2 weeks ago and feel nothing. Is it working?', a: "Two weeks is too early to judge efficacy. Most men don't notice measurable changes until weeks 3–4 at earliest. If you're on injections, you may feel a \"second wind\" effect as testosterone peaks 24–48 hours post-injection before feeling flat again — this is normal until steady-state is reached (typically week 4–6)." },
      { q: "My levels are \"in range\" but I still feel off. What's wrong?", a: 'Request a full hormone panel: SHBG, free testosterone (direct dialysis or calculated), E2 (sensitive assay), TSH, cortisol, and fasting insulin. "In range" total testosterone with high SHBG or low free T explains most cases of persistent symptoms.' },
      { q: 'How long until I reach stable levels?', a: 'With injectable testosterone cypionate or enanthate, steady-state is reached after approximately 5 half-lives. At a standard weekly injection schedule, this means stable levels by weeks 4–6.' },
      { q: 'Will I need to stay on TRT forever?', a: "Most men who have genuine clinical hypogonadism (T consistently below 300 ng/dL with symptoms) find that the benefits justify continued treatment. Men using TRT as a \"performance\" tool often cycle off — but should plan for a 3–12 month natural production recovery period." }
    ]
  },
];

// ── CLINIC REVIEWS ────────────────────────────────────────────────────────────
// Ranks are assigned by score descending. All 11 published clinics included.
const CLINICS = {
  'trt-nation': {
    name: 'TRT Nation',
    slug: 'trt-nation',
    score: 9.1,
    rank: 1,
    tagline: 'Best value — most clinic for the lowest true cost',
    price: '$99/mo',
    priceDetail: 'Unlimited consults, all labs included',
    badge: 'Best value',
    affiliateUrl: 'https://trtnation.com',
    lastReviewed: 'Q2 2026',
    pros: ['Unlimited physician consults included', '10+ medication options including compounded', 'Lowest total cost in category', 'Self-injection guidance included', 'Ancillary medications available (HCG, Anastrozole, enclomiphene)'],
    cons: ['No 24/7 support — business hours only', 'Wait times can be 2–4 days for non-urgent', 'Some states restricted (see legality map)'],
    verdict: 'TRT Nation earns its #1 rank by delivering the most complete package at the lowest price. At $99/month with unlimited consults and all lab work included, the math is simple: most competitors charge $150–$250/month and still bill separately for labs. For men who know what they want and just need a reliable, affordable script, TRT Nation is the clear choice. The only meaningful trade-off is async-only communication — you won’t get a physician on the phone at midnight, but for a routine TRT protocol, you won’t need one.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 9, detail: '$99/mo all-in. No surprise lab charges, no add-ons. One of the simplest pricing structures in the category.' },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Board-certified physicians, async consult model. Prescriptions written for valid patients within their licensed states.' },
      { num: 3, name: 'Medication menu', score: 9, detail: 'Full testosterone menu (cypionate/enanthate), HCG, anastrozole, enclomiphene, B-12 injections. More than most competitors.' },
      { num: 4, name: 'Consultation experience', score: 9, detail: 'Intake form → physician review → prescription. Most users get their protocol within 48–72 hours. No phone required.' },
      { num: 5, name: 'Lab work & monitoring', score: 8, detail: 'Quarterly labs included in subscription. Covers total T, free T, estradiol, SHBG, CBC, metabolic panel. Adequate.' },
      { num: 6, name: 'Shipping & fulfillment', score: 9, detail: 'Pharmacy network ships to all 50 states (excluding NY, NJ, CA for some formulations). Typical 3–5 day delivery.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Ancillary protocol support included. Physician will adjust or add HCG/anastrozole as needed at no extra consult cost.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Email and ticket-based. Response within 1–2 business days. Not instant, but thorough and US-based.' },
      { num: 9, name: 'Cancellation flexibility', score: 9, detail: 'Cancel anytime via account settings. No hoops. No retention calls. One of the cleanest cancellation flows.' },
      { num: 10, name: 'Overall value', score: 10, detail: 'At $99/month all-in vs $150–250 for comparable services, TRT Nation wins on total cost over 6 months by $300–900.' },
    ],
  },
  'fountain-trt': {
    name: 'Fountain TRT',
    slug: 'fountain-trt',
    score: 8.8,
    rank: 2,
    tagline: 'Best concierge experience — premium without complexity',
    price: '$199/4wk',
    priceDetail: 'Everything bundled — no surprise billing',
    badge: 'Best concierge',
    affiliateUrl: 'https://fountaintrt.com',
    lastReviewed: 'Q2 2026',
    pros: ['Flat-rate bundle — zero surprise charges', 'Dedicated care coordinator assigned to every patient', 'Board-certified urologist prescribers', '24/7 text/chat support', 'Comprehensive hormone panel on intake'],
    cons: ['$199/mo is 2x TRT Nation', 'Only available in 30+ states (not all)', 'Longer onboarding — 5–7 days typical'],
    verdict: 'Fountain TRT is for men who want a premium, hands-on experience without navigating complexity themselves. At $199/month everything is included — consults, labs, medication, and a dedicated care coordinator. The physician quality is genuinely strong (urologists, not GPs), and the 24/7 text line means you can get questions answered fast. The tradeoff is price: you pay roughly double TRT Nation for a meaningfully better experience if you value time and access. If budget is the primary constraint, TRT Nation wins. If premium service and physician depth matter, Fountain is the pick.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 10, detail: 'True all-in pricing. $199 covers everything. No billing surprises, no separate lab invoices, no pharmacy markups.' },
      { num: 2, name: 'Medical oversight', score: 9, detail: 'Board-certified urologists (not NPs or GPs). Full chart review before any prescription. Among the strongest oversight in the space.' },
      { num: 3, name: 'Medication menu', score: 8, detail: 'Standard TRT menu: testosterone cypionate/enanthate, HCG, anastrozole. No experimental or compounded options.' },
      { num: 4, name: 'Consultation experience', score: 10, detail: 'Dedicated care coordinator + physician. Onboarding is thorough — 45-min intake, full hormone panel, individualized protocol. 5–7 days start to finish.' },
      { num: 5, name: 'Lab work & monitoring', score: 9, detail: 'Initial comprehensive panel (15+ biomarkers). Quarterly follow-ups. Data presented clearly with physician walkthrough.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Reliable pharmacy network. 3–5 day shipping. Cold-chain handling for sensitive medications.' },
      { num: 7, name: 'Side effect handling', score: 9, detail: 'Direct text line to care coordinator. Side effects addressed same-day. Protocol adjustments without new consult fees.' },
      { num: 8, name: 'Customer support', score: 10, detail: '24/7 text/chat. Phone support 8am–8pm EST. Care coordinator assigned for continuity. Among the best in category.' },
      { num: 9, name: 'Cancellation flexibility', score: 8, detail: '30-day notice required. No hoops, but the minimum commitment is longer than pure-monthly competitors.' },
      { num: 10, name: 'Overall value', score: 8, detail: '$199/mo with full support is fair for men who want certainty and access. Double TRT Nation cost is justified by service quality.' },
    ],
  },
  'peter-md': {
    name: 'Peter MD',
    slug: 'peter-md',
    score: 8.5,
    rank: 3,
    tagline: 'Best value all-in — injectable TRT at the lowest true cost in the US',
    price: '$79/mo',
    priceDetail: 'All-in: meds, labs, physician consults, free shipping',
    badge: 'Best value',
    affiliateUrl: 'https://getpetermd.com',
    lastReviewed: 'Q2 2026',
    pros: ['$79/mo all-in — lowest price in our review set, medication and labs included', 'Licensed physician consults on every case — LegitScript verified', '20,000+ Trustpilot reviews at 4.9/5 average', 'Covers 48 US states — broader reach than most competitors', 'Enclomiphene (oral, fertility-sparing) option available alongside injectable TRT', 'Price match guarantee: 20% discount if you find a better all-in price'],
    cons: ['Cancellation requires contacting support — not self-serve (30-day notice)', 'Short consultation times reported by some users on Reddit', 'Limited ancillary menu vs. Fountain TRT or Defy Medical', 'No 24/7 support — async/ticket model'],
    verdict: 'Peter MD is the best value all-in TRT clinic in the US market, full stop. At $79/month with labs, physician consults, and medication included — free shipping — it undercuts TRT Nation by $20/month while matching the all-in model. The 4.9/5 Trustpilot score from over 20,000 reviews is the strongest customer satisfaction signal in our review set. The price match guarantee is unique in the category. If you want the lowest friction, lowest cost entry point to injectable TRT with a real physician review, Peter MD is the clear pick. Trade-offs: cancellation requires contacting support (vs. TRT Nation self-serve), and consultation times can be brief. But on total cost and basic service quality, Peter MD is the value leader.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 10, detail: '$79/mo all-in — medications, labs, physician consults, free shipping. Price match guarantee: 20% discount if you find a better all-in price. Simplest and most consumer-friendly pricing in our review set.' },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Licensed physicians review every case. LegitScript verified. Covers 48 states — broader licensed footprint than Fountain TRT, Marek, or Defy Medical. Async consult model with physician-signed prescriptions.' },
      { num: 3, name: 'Medication menu', score: 8, detail: 'Testosterone cypionate injectable as primary. Enclomiphene (oral, fertility-sparing) available. HCG and NAD+ injections as add-ons. More varied than Low T Center or SynergenX, less than Defy Medical peptide menu.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: 'Online 15-second assessment → lab order via Quest → physician video consult → medication shipped. Most users report 48–72 hour turnaround. No phone required. LegitScript verification signals legitimate operation.' },
      { num: 5, name: 'Lab work & monitoring', score: 8, detail: 'Quest Diagnostics labs included. Quarterly monitoring on file. Ongoing physician access for lab result discussions. Adequate monitoring — not as comprehensive as Hone Health 40-biomarker panel.' },
      { num: 6, name: 'Shipping & fulfillment', score: 9, detail: 'Free shipping on all medications. Delivered to door, plain packaging. 3–5 day typical delivery. 48-state coverage — ships to most of the US excluding a small number of restricted states.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Unlimited provider access included in plan. HCG and anastrozole available as ancillaries for managing side effects. Physician adjusts protocol at follow-up. Included, not add-on.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Async/ticket-based model — not instant. Response within 1–2 business days typical. No 24/7 line. LegitScript status provides accountability signal. Some Reddit reports of short consult times.' },
      { num: 9, name: 'Cancellation flexibility', score: 7, detail: '30-day notice required, contact support to cancel — not self-serve. No retention call mentioned. Better than SynergenX and Low T Center for stated simplicity, but TRT Nation has the cleanest cancel flow.' },
      { num: 10, name: 'Overall value', score: 9, detail: '$79/mo all-in is the lowest true cost in our review set — beating TRT Nation at $99/mo. For a patient who wants injectable TRT with labs and physician access at minimum cost, Peter MD wins on value. Price match guarantee adds further consumer protection.' },
    ],
  },
  'hone-health': {
    name: 'Hone Health',
    slug: 'hone-health',
    score: 8.4,
    rank: 4,
    tagline: 'Longevity-focused — best for men treating TRT as part of a broader health plan',
    price: '$149/mo',
    priceDetail: 'Includes advanced biomarker panel and physician-guided protocol',
    badge: null,
    affiliateUrl: 'https://hone.com',
    lastReviewed: 'Q2 2026',
    pros: ['Comprehensive 40+ biomarker panel on intake', 'Physician-guided protocol with longevity framing', 'Covers testosterone, thyroid, metabolic health', 'Good for men already health-conscious', 'Strong app experience and progress tracking'],
    cons: ['Pricier than bare-bones TRT clinics', 'More clinical than casual — not for first-timers', 'TRT is one offering among many — less specialized than dedicated TRT clinics'],
    verdict: 'Hone Health positions itself as a men`s health platform first, TRT clinic second. That framing matters: their intake and ongoing care accounts for broader metabolic health, not just testosterone. If you`re treating TRT as one pillar of a longevity or anti-aging strategy — and you want the data to match — Hone delivers. The 40+ biomarker panel is genuinely more comprehensive than most competitors. But that depth comes with a higher price ($149/mo) and a more clinical feel. If you want a simple, affordable TRT script and nothing else, look at TRT Nation. If you want TRT inside a broader health optimization context, Hone is the right call.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 8, detail: '$149/mo includes labs and physician consults. Clear on website. Not the cheapest, but no surprise billing.' },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Physicians with men`s health / endocrinology background. More holistic than most dedicated TRT clinics.' },
      { num: 3, name: 'Medication menu', score: 8, detail: 'TRT menu plus thyroid support, peptides (where legal), and metabolic medications. Broader than pure TRT clinics.' },
      { num: 4, name: 'Consultation experience', score: 9, detail: 'Detailed intake including health history, goals, current labs. Physician reviews and builds a protocol. 5–7 days typical.' },
      { num: 5, name: 'Lab work & monitoring', score: 10, detail: '40+ biomarkers on intake — testosterone panel, thyroid (TSH, T3, T4), lipids, metabolic panel, inflammatory markers, vitamin D, B12. Best-in-class monitoring.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Pharmacy network with 3–5 day delivery. Reliable. Temperature-sensitive formulations handled properly.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Physician-guided. Adjustments made based on lab results. Protocol is iterative and data-driven.' },
      { num: 8, name: 'Customer support', score: 8, detail: 'App-based messaging with physician response in 1–2 days. Not instant but thorough and documented.' },
      { num: 9, name: 'Cancellation flexibility', score: 8, detail: 'Monthly subscription, cancel anytime. No long-term lock-ins.' },
      { num: 10, name: 'Overall value', score: 8, detail: '$149/mo for a comprehensive health platform is justified for men focused on longevity. Not the best for cost-only buyers.' },
    ],
  },
  'jack-health': {
    name: 'Jack Health',
    slug: 'jack-health',
    score: 8.0,
    rank: 5,
    tagline: 'Best Canadian option — gel-based TRT with licensed clinicians and pharmacy delivery',
    price: '$90/quarter',
    priceDetail: '~$30/mo program fee; pharmacy medication separate',
    badge: null,
    affiliateUrl: 'https://jack.health',
    lastReviewed: 'Q2 2026',
    pros: ['$90/quarter (~$30/mo) is highly competitive in Canadian market', 'Licensed Canadian clinicians personally review each application', 'Health Canada-authorized pharmacy ships in plain packaging within 24–48 hours', 'Testosterone gel only — no injections needed, simpler self-administration', 'Many plans cover TRT medication; Jack Health assists with reimbursement claims', 'Free health questionnaire — no credit card required to start'],
    cons: ['Gel only — no injectable option for patients who prefer or need injections', 'Not available in Quebec, Manitoba, New Brunswick, Nova Scotia, Yukon, PEI', 'Medication cost is separate from program fee (not all-in pricing)', 'Medication must be sourced through Jack Health pharmacy — less flexible than clinics with pharmacy network options'],
    verdict: 'Jack Health is the best gel-based TRT option for Canadian men who want licensed clinician oversight at a reasonable price. At $90/quarter (~$30/month) for the program fee, it is highly competitive — and many Canadian insurance plans cover the medication component separately, making the effective cost potentially even lower. The catch: gel-only delivery rules out men who prefer injectable testosterone, and Jack Health is not available in six provinces. For Canadian men in Ontario, British Columbia, Alberta, or Saskatchewan who want gel TRT, Jack Health is the clear pick. For those needing or preferring injections, Science & Humans or Gameday Men`s Health are better next options.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 9, detail: '$90/quarter program fee clearly stated. Free questionnaire to start — no credit card required. Medication cost separate but clearly disclosed. Better than SynergenX or Low T Center where pricing is opaque. Canadian insurance reimbursement assistance adds further value clarity.' },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Licensed Canadian clinicians personally review each application. Not a fully automated questionnaire-to-script model — real clinician judgment on each case. Covers Ontario, BC, Alberta, Saskatchewan, and most other provinces except Quebec and others.' },
      { num: 3, name: 'Medication menu', score: 7, detail: 'Testosterone gel only — no injectable option. Broader menu for other concerns: ED (sildenafil/tadalafil), hair loss (finasteride), weight loss (GLP-1). Gel TRT is effective but limits patients who prefer or medically require injection.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: 'Free online health questionnaire. No credit card required. Licensed clinician reviews personally. If approved, prescription sent to Health Canada-authorized pharmacy within 24–48 hours. Simpler and faster than in-person clinic models.' },
      { num: 5, name: 'Lab work & monitoring', score: 7, detail: 'Blood work included in ongoing care. Quarterly monitoring cadence implied. Individual clinician review on each case provides baseline accountability. Less detail on biomarker scope than Hone Health or Defy Medical.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Plain, unmarked packaging for privacy. 24–48 hour shipping from Health Canada-authorized pharmacy. Free shipping included. Consistent with or faster than most US competitors.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Ongoing care via secure messaging with care team. Clinician adjusts protocol based on results. DHT gel side effect monitoring (skin irritation at application site) explicitly part of ongoing care.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Secure messaging with care team for ongoing questions. No phone number prominently listed — async-first model. Mixed Trustpilot reviews: positive on convenience and delivery speed, some concerns about depth of ongoing support.' },
      { num: 9, name: 'Cancellation flexibility', score: 8, detail: 'Month-to-month program structure implied. No long-term contract visible. Program fee is $90/quarter so exposure per quarter is manageable. No retention call or hold tactics reported.' },
      { num: 10, name: 'Overall value', score: 8, detail: '$90/quarter (~$30/mo) program fee is highly competitive for Canadian market. Medication separate but insurance reimbursement helps. Strong value for Canadian men who want licensed clinician oversight and prefer gel delivery. Not the cheapest if medication costs are factored in, but total package is competitive.' },
    ],
  },
  'marek-health': {
    name: 'Marek Health',
    slug: 'marek-health',
    score: 8.0,
    rank: 6,
    tagline: 'Medical-first — best for men who want a traditional physician relationship',
    price: '$140/mo',
    priceDetail: 'Includes all labs, with optional medication add-ons',
    badge: null,
    affiliateUrl: 'https://marekhealth.com',
    lastReviewed: 'Q2 2026',
    pros: ['Physician-led practice, not a midlevel model', 'Full hormone panel + metabolic panel on intake', 'Ancillary protocol support included (HCG, AI)', 'Transparent pricing with no surprise charges', 'Good protocol documentation and lab history'],
    cons: ['Onboarding takes 7–10 days (longest in category)', 'No 24/7 support — business hours only', 'Ships to 38 states, not all 50', 'UI/website is functional but dated'],
    verdict: 'Marek Health takes a traditional medical practice approach to online TRT — longer intake, physician-first model, slower but thorough. At $140/month with labs included, it sits between budget clinics and premium concierge services. The physician model means you are getting a real doctor relationship, not an NP with 3 minutes. The tradeoff is time: 7–10 days from signup to first injection is the slowest onboarding in our review set. If you have patience and value a physician-led practice over speed, Marek is a strong pick. If you want something faster and cheaper, TRT Nation at $99/month undercuts it by $41/month with a 48-hour turnaround.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 8, detail: '$140/mo base with labs included. Pharmacy add-ons are clearly priced. Minor variability based on medication choice but no hidden fees.' },
      { num: 2, name: 'Medical oversight', score: 9, detail: 'Physician-led practice. Every prescription is reviewed by a licensed MD. This is the most rigorous prescriber model in our review set.' },
      { num: 3, name: 'Medication menu', score: 8, detail: 'Testosterone cypionate and enanthate, HCG, anastrozole, enclomiphene. Standard TRT menu with some peptide options in select states.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: '7–10 day onboarding: intake form → physician chart review → protocol discussion → prescription. Thorough but slow. No live video required.' },
      { num: 5, name: 'Lab work & monitoring', score: 9, detail: 'Full hormone panel + CBC + metabolic panel on intake. Quarterly follow-ups. Results reviewed by physician with written summary.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Ships to 38 states via partner pharmacy network. Typical 3–5 day delivery. Cold-chain medications handled appropriately.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Physician reviews side effect reports and adjusts protocol. Ancillary medications (AI, HCG) are part of the program, not add-ons.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Email and web-based support during business hours. Response within 1 business day. Not instant, not 24/7.' },
      { num: 9, name: 'Cancellation flexibility', score: 8, detail: '30-day notice to cancel. No cancellation fee. One email to support initiates the process.' },
      { num: 10, name: 'Overall value', score: 7, detail: '$140/mo with physician-led care is fair. Slightly more expensive than Hone Health with less tech-forward experience. Strong value if physician quality is the priority.' },
    ],
  },
  'defy-medical': {
    name: 'Defy Medical',
    slug: 'defy-medical',
    score: 7.7,
    rank: 7,
    tagline: 'Protocol customization — best for men with complex hormone histories',
    price: '$199/mo',
    priceDetail: 'All-inclusive: consults, labs, and pharmacy fulfillment',
    badge: null,
    affiliateUrl: 'https://defymedical.com',
    lastReviewed: 'Q2 2026',
    pros: ['Deep protocol customization — treats complex cases', 'Full hormone panel + peptide therapy options', 'Strong ancillary protocol support (IV/Injection)', 'Physician specialists in hormone medicine', 'Good for men who have tried TRT before and want refinement'],
    cons: ['Most expensive in review set at $199/mo', 'Less accessible for first-time TRT patients', 'Some states excluded from service', 'Website UX is outdated and confusing'],
    verdict: 'Defy Medical is a specialty clinic, not a general TRT entry point. At $199/month all-inclusive, it is priced for men who have already done their research and know they want a deeper protocol than the standard "200mg/week" starter kit. If you are new to TRT and just want a reliable script, there are better-priced options (TRT Nation at $99, Marek at $140). But if you have run TRT before, have complex hormone issues, want peptide therapy, or have had poor responses to standard protocols, Defy Medical is purpose-built for you. The physician depth is real. The price is justified for the right patient.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 7, detail: '$199/mo all-inclusive sounds simple but the menu complexity makes it hard to calculate true cost for add-ons. Better than clinics with surprise lab bills, worse than flat-rate transparent competitors.' },
      { num: 2, name: 'Medical oversight', score: 9, detail: 'Physician specialists in hormone medicine, not generalists. Every patient gets physician-reviewed protocol with documented rationale. Among the strongest oversight model in our review set.' },
      { num: 3, name: 'Medication menu', score: 9, detail: 'TRT menu plus peptide therapy (BPC-157, TB-500, CJC-1295/Ipamorelin), growth hormone optimization, and advanced ancillaries. The widest menu in our review set.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: 'Initial consult is comprehensive — 45–60 minutes with a hormone specialist. Protocol is individualized, not templated. 10–14 days start to finish.' },
      { num: 5, name: 'Lab work & monitoring', score: 9, detail: 'Comprehensive hormone panel + metabolic + inflammatory markers on intake. Quarterly monitoring with physician review. More detailed than any other clinic in our review set.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Specialty pharmacy network handles peptides and biologics. Standard 3–5 day delivery. Temperature-sensitive items properly packaged.' },
      { num: 7, name: 'Side effect handling', score: 9, detail: 'Strong protocol support for complex cases. Side effects are treated as medical issues, not support tickets. Physician accessible for adjustments.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Email and web portal. Response within 1–2 business days. Not a high-volume clinic — more boutique, which means less churn-and-burn support.' },
      { num: 9, name: 'Cancellation flexibility', score: 7, detail: '30-day notice. No retention calls. Clean process. Not as frictionless as TRT Nation but no major obstacles.' },
      { num: 10, name: 'Overall value', score: 7, detail: '$199/mo with peptide options and specialist physicians is the highest price in our review set. Justified for men with complex needs, not for first-timers or cost-sensitive buyers.' },
    ],
  },
  'synergenx-health': {
    name: 'SynergenX Health',
    slug: 'synergenx-health',
    score: 7.2,
    rank: 8,
    tagline: 'In-person + telehealth hybrid — best for men in TX/IL who want hands-on TRT care',
    price: '~$155/mo',
    priceDetail: '~$105/mo insured; consultation required for exact quote',
    badge: null,
    affiliateUrl: 'https://synergenxhealth.com',
    lastReviewed: 'Q2 2026',
    pros: ['Free consultation + free testosterone test (ongoing promotion)', '21 in-person TX/IL locations — real clinical care, not just a telehealth portal', 'Broad insurance network: Aetna, BCBS, Cigna, UHC, GEHA, Meritain, APWU, HealthPartners and more', 'InBody composition scan + ANS testing for comprehensive baseline', 'Self-Inject program for ongoing at-home TRT with clinical oversight', 'Peptide therapy available (Sermorelin, PT-141)', 'GLP-1 weight loss programs (ancillary service for existing patients)', 'FSA/HSA eligible at all locations'],
    cons: ['No public self-pay pricing — must call or consult for a quote (major transparency gap)', 'Only 21 locations: TX + IL only; no national telehealth-first model', 'NP/PA primary providers with physician oversight — less physician-direct than Marek Health', 'Glassdoor: call center management complaints, 3.0/5 compensation score', 'Yelp reviews mixed: positive on clinical care, concerns about phone responsiveness', 'Insurance-dependent cost — uninsured patients face uncertain pricing', "Women's HRT is a newer service (July 2025 expansion)"],
    verdict: "SynergenX Health occupies a distinct niche: it combines the physical presence of a traditional doctor's office — 21 locations across Texas and Illinois — with a Self-Inject program that ships custom-dosed TRT to your door. If you live near one of their clinics, this is one of the most physician-dense, hands-on TRT experiences you can get. The free consultation + free testosterone test removes the barrier to entry. Insurance acceptance is broad. The catch: SynergenX doesn't publish its self-pay price. You must call or come in for a quote, which is a significant transparency gap compared to clinics like TRT Nation that state $99/mo flat. Score: 7.2/10 — genuine in-person value if you're in-network, clouded by opaque pricing.",
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 5, detail: "No published self-pay price. Must call or consult for a quote. This is a meaningful gap compared to clinics that state pricing upfront." },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Licensed NPs and FNPs with named physician oversight. Specific provider names listed on each location page. 200+ staff across 21 locations. Good accountability signal.' },
      { num: 3, name: 'Medication menu', score: 7, detail: 'Injectable testosterone cypionate (custom-dosed). Self-Inject program ships prefilled syringes. Peptides (Sermorelin, PT-141) available as add-ons. HCG and anastrozole implied but not explicitly listed on public pricing page.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: 'Free consultation + free T test (ongoing). In-person intake includes InBody scan, ANS testing, and full hormone panel. 67 biomarker panel for women; comprehensive baseline for men. Walk-ins accepted. No referral needed.' },
      { num: 5, name: 'Lab work & monitoring', score: 7, detail: 'Comprehensive lab panel on intake. Quarterly monitoring implied. InBody + ANS testing is above standard. Some lab billing may occur separately — not confirmed as all-inclusive.' },
      { num: 6, name: 'Shipping & fulfillment', score: 7, detail: 'Self-Inject program delivers custom prefilled syringes to your door. Free automatic shipping for supplies. In-clinic pickup also an option. Reliable when pharmacy partner is functioning well.' },
      { num: 7, name: 'Side effect handling', score: 7, detail: "Site states: 'your provider will actively monitor your labs and adjust as needed to keep you safe and on track.' Dose adjustments included in ongoing care. No explicit charge for protocol changes." },
      { num: 8, name: 'Customer support', score: 6, detail: 'Phone support (888-219-7259) across 21 locations. Glassdoor: call center management criticized; slow response on some issues. Yelp reviews for The Woodlands positive. Phone responsiveness varies by location.' },
      { num: 9, name: 'Cancellation flexibility', score: 7, detail: 'No visible long-term contract or cancellation fee. "Affordable self-pay options available." Month-to-month structure implied by Self-Inject subscription model. No explicit cancel policy published.' },
      { num: 10, name: 'Overall value', score: 8, detail: 'For insured patients, the $105/mo price is competitive with TRT Nation. The in-person care model justifies the price. The transparency gap on self-pay pricing is a real concern. If you have insurance and are in TX/IL, this is excellent value. Self-pay uncertainty is a legitimate weakness.' },
    ],
  },
  'low-t-center': {
    name: 'Low T Center',
    slug: 'low-t-center',
    score: 6.4,
    rank: 9,
    tagline: 'Price leader for in-person clinic networks — best value for insured patients in covered states',
    price: '$105/mo',
    priceDetail: 'Insured rate; $155/mo self-pay; free testosterone test',
    badge: null,
    affiliateUrl: 'https://lowtcenter.com',
    lastReviewed: 'Q2 2026',
    pros: ['$105/mo with insurance / $155/mo self-pay — lowest published price in category', '40+ locations across 10 states — widest in-person footprint in review set', 'Free testosterone test (ongoing)', 'Custom-dosed prefilled syringes shipped monthly via Self-Inject program', 'Broad insurance network: BCBS, Cigna, APWU, HealthPartners, Gravie, PHCS', 'Medical Director Dr. John Hampton III (board-certified)'],
    cons: ['NP/PA primary provider model — less physician-direct than Marek Health or Defy Medical', 'Inconsistent location quality — Reddit and Yelp report prescription delays and staff turnover', 'Prescription delays reported in multiple state subreddits (NC, TX, IL)', 'Staff turnover and management issues at some locations (Glassdoor)', 'Medication menu limited to injection-only — no troches, gels, or compounded options', 'No published self-pay price on lowtcenter.com — must find via blog post'],
    verdict: 'Low T Center is the price leader among in-person clinic networks — $105/month with insurance and $155/month without puts it in the same ballpark as TRT Nation for affordability. The problem is execution: Reddit and Yelp consistently report prescription delays, staff turnover, and inconsistent in-clinic quality. The same ownership runs SynergenX with a more polished in-person experience. If you are in an area with a consistently-rated Low T Center location, the price is hard to beat. If your local center has bad reviews, the price advantage evaporates fast.',
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 7, detail: "Published prices exist — but only in a blog article (June 2023, updated May 2026), not on the main pricing page. $105/mo insured / $155/mo self-pay. This creates a discovery problem: the first-time visitor has to dig for the actual cost." },
      { num: 2, name: 'Medical oversight', score: 6, detail: 'NP/PA primary providers with physician oversight. Medical Director Dr. John Hampton III is named and credentialed. 40+ locations means variable oversight quality. Better than pure telehealth but less physician-direct than Marek Health.' },
      { num: 3, name: 'Medication menu', score: 6, detail: 'Testosterone cypionate via Self-Inject program (prefilled, custom-dosed). HCG and anastrozole available as ancillaries. Injection-only — no topical/gel options. Peptides not listed. Less flexible than Fountain TRT or Hone Health.' },
      { num: 4, name: 'Consultation experience', score: 7, detail: 'Free testosterone test removes the barrier to entry. Walk-ins accepted at most locations. In-person intake is straightforward. However, reported wait times for new patient appointments vary significantly by location.' },
      { num: 5, name: 'Lab work & monitoring', score: 6, detail: 'Lab work included with membership. Quarterly monitoring implied but frequency not explicitly stated. Some locations may bill lab work separately — not confirmed as all-inclusive. InBody + ANS scan not mentioned.' },
      { num: 6, name: 'Shipping & fulfillment', score: 7, detail: 'Self-Inject program ships monthly — custom-dosed, prefilled syringes. Free automatic refills. Reliability issues reported when pharmacy partner has delays. In-clinic pickup also available. Overall execution is consistent when the system works.' },
      { num: 7, name: 'Side effect handling', score: 6, detail: 'Provider adjusts protocol based on follow-up labs. Included in ongoing care. However, the reported delays in prescription refills can interrupt treatment continuity — which is a side-effect handling gap in practice.' },
      { num: 8, name: 'Customer support', score: 4, detail: 'Consistent negative reviews across Reddit and Yelp about phone responsiveness, prescription delays, and staff turnover. Some locations have 4-year satisfied patients — but the spread suggests high location-level variance. Lowest score in our review set for support.' },
      { num: 9, name: 'Cancellation flexibility', score: 6, detail: 'Month-to-month implied by Self-Inject subscription model. No visible long-term contract. "Cancel anytime" language found in marketing materials. Not as explicitly frictionless as TRT Nation but no major obstacles reported.' },
      { num: 10, name: 'Overall value', score: 7, detail: '$105/mo insured is the best value in our in-person clinic group. $155/mo self-pay is competitive with TRT Nation. The value case collapses if your local center has poor reviews — the price is only worth it if the execution matches. Strong for price-sensitive insured patients in covered states.' },
    ],
  },
  'elmvale-health': {
    name: 'Elmvale Health',
    slug: 'elmvale-health',
    score: 7.2,
    rank: 10,
    tagline: "Canada's top-rated online TRT clinic",
    price: '~$299/mo CAD',
    priceDetail: '~$199–$299 CAD/month; ~$89 CAD for follow-up labs',
    badge: 'NEW',
    affiliateUrl: null,
    affiliateNote: '[Affiliate program — Direct pending]',
    lastReviewed: 'Q2 2026',
    pros: ['Canadian-licensed physicians and pharmacy', 'Competitive Canadian pricing (below US equivalents in CAD terms)', 'Comprehensive initial blood panel included', 'Free Canada-wide shipping', 'HCG and anastrozole available as add-ons', 'No referral required', 'Online consultation takes under 15 minutes'],
    cons: ['Only available to Canadian residents', 'Limited US availability (not currently operating in US market)', 'Smaller clinic footprint vs. Hone or Defy', 'Affiliate program status unclear (pending confirmation)', 'Less brand recognition outside Canada'],
    verdict: "Elmvale Health is a strong option for Canadian men seeking physician-supervised TRT at competitive prices. The clinic's Canadian licensing and pharmacy relationships provide a level of trust that some US-based competitors lack. At ~$299 CAD/month, it's priced competitively against US clinics once exchange rates are factored in. The main limitation is availability — Elmvale only serves Canadian residents, which limits its addressable market from a US-centric comparison site. However, for the Canadian audience TRT Compass reaches, Elmvale fills an important gap: a domestic, licensed provider at a fair price. If you're in Canada and researching TRT options, Elmvale should be on your shortlist. The medical oversight is solid, the pricing is transparent, and the process is streamlined.",
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 7, detail: 'Clear pricing on site, no hidden fees mentioned. ~$199–$299 CAD/month with follow-up labs at ~$89 CAD. Competitive vs. US clinics when factoring exchange rates.' },
      { num: 2, name: 'Medical oversight', score: 8, detail: 'Canadian MDs, blood work required before prescribing. Licensed Canadian physicians lead each case — stronger oversight than many US telehealth mills.' },
      { num: 3, name: 'Medication menu', score: 8, detail: 'Compounded through licensed Canadian pharmacy. Testosterone replacement + HCG + anastrozole as add-ons. Standard TRT menu, high-quality sourcing.' },
      { num: 4, name: 'Consultation experience', score: 8, detail: 'Fully online, no in-person visits required. Online consultation takes under 15 minutes. Physician reviews and responds within days.' },
      { num: 5, name: 'Lab work & monitoring', score: 8, detail: 'Comprehensive initial blood panel included in consult. Follow-up labs ~$89 CAD. Adequate ongoing monitoring cadence.' },
      { num: 6, name: 'Shipping & fulfillment', score: 8, detail: 'Free shipping across Canada. Licensed Canadian pharmacy fulfillment. Reliable and consistent.' },
      { num: 7, name: 'Side effect handling', score: 7, detail: 'Physician reviews side effects and adjusts protocol. HCG and anastrozole available as needed. Included in ongoing care.' },
      { num: 8, name: 'Customer support', score: 7, detail: 'Smaller team means more personalized attention, but less infrastructure. Response within 1–2 business days typical.' },
      { num: 9, name: 'Cancellation flexibility', score: 7, detail: 'Month-to-month, reasonable notice period. No long-term lock-ins. No retention call tactics reported.' },
      { num: 10, name: 'Overall value', score: 8, detail: 'Strong value for Canadians at ~$299 CAD/month. Below US equivalents in CAD terms — a $249 USD clinic is ~$340 CAD, making Elmvale competitive.' },
    ],
  },
  'nexalin-technology': {
    name: 'Nexalin Technology',
    slug: 'nexalin-technology',
    score: 6.9,
    rank: 11,
    tagline: 'Next-generation hormone therapy with DAO therapy protocols',
    price: '$299–$599/mo',
    priceDetail: 'Tiered by protocol intensity; Doppler monitoring included in premium tiers',
    badge: 'NEW',
    affiliateUrl: null,
    affiliateNote: '[Affiliate program — Direct pending]',
    lastReviewed: 'Q2 2026',
    pros: ['Multi-marker hormone optimization (not just testosterone)', 'Doppler ultrasound-guided injection protocols for precision dosing', 'DAO enzyme therapy for hormone metabolism optimization', 'Comprehensive ongoing blood monitoring included in premium tiers', 'Science-forward approach with published protocols', 'Medical team includes endocrinologists and hormone specialists', 'Telehealth + in-person options for flexibility'],
    cons: ['Higher cost than standard TRT clinics', 'Complex protocol may be overkill for men with straightforward low T', 'Affiliate program status unclear (pending confirmation)', 'Smaller patient base = less community feedback available', 'Site has limited public pricing detail for some tiers', 'Enrollment process requires more medical screening'],
    verdict: "Nexalin Technology is for men who want more than basic TRT. Where most clinics offer testosterone replacement, Nexalin offers hormone ecosystem optimization — addressing the full endocrine picture rather than just raising a single number. The pricing is premium, and the protocol complexity isn't necessary for everyone. But for men with complex hormonal needs, a history of suboptimal TRT outcomes, or a preference for science-forward protocols, Nexalin fills an important niche. The Doppler-guided injection approach and multi-marker monitoring represent a meaningful step up from commodity TRT. At $299–$599/month, it's positioned between standard telehealth clinics and concierge endocrinology practices. That positioning makes sense for the target customer: a man in his late 30s to early 60s who's done the research, tried basic TRT, and wants something more sophisticated.",
    rubric: [
      { num: 1, name: 'Pricing transparency', score: 7, detail: 'General pricing ranges are clear on site. Tier pricing is less transparent — some advanced protocols require consultation for exact cost. Better than SynergenX or Low T Center on disclosure.' },
      { num: 2, name: 'Medical oversight', score: 9, detail: 'Endocrinologist-led, Doppler-guided injection protocols. Among the strongest medical team in our review set. Precision dosing through imaging guidance.' },
      { num: 3, name: 'Medication menu', score: 9, detail: 'Bioidentical hormones, precision delivery via Doppler-guided protocols. DAO enzyme therapy included in premium tiers. Advanced menu well beyond standard TRT clinics.' },
      { num: 4, name: 'Consultation experience', score: 7, detail: 'More intensive onboarding than basic clinics — more medical screening required. Comprehensive initial intake. 7–10 days typical start to finish.' },
      { num: 5, name: 'Lab work & monitoring', score: 9, detail: 'Comprehensive ongoing blood monitoring included in premium tiers. Multi-marker approach: estrogen, cortisol, thyroid, metabolic alongside testosterone. Among the most thorough monitoring in our review set.' },
      { num: 6, name: 'Shipping & fulfillment', score: 7, detail: 'Pharmacy network delivers to most states. 3–5 day typical delivery. Telehealth + in-person options — some protocols require clinic visits for Doppler imaging.' },
      { num: 7, name: 'Side effect handling', score: 8, detail: 'Physician-guided protocol adjustments based on multi-marker monitoring. DAO therapy addresses hormone metabolism side effects proactively.' },
      { num: 8, name: 'Customer support', score: 8, detail: 'Specialized, personalized approach. Smaller patient base means more individual attention. Response within 1–2 days.' },
      { num: 9, name: 'Cancellation flexibility', score: 7, detail: 'Month-to-month, reasonable terms. No long-term lock-ins. Clean cancellation process implied.' },
      { num: 10, name: 'Overall value', score: 7, detail: 'Premium pricing reflects premium approach — value depends on patient needs. More than basic TRT, less than concierge endocrinology. Right for the right patient.' },
    ],
  },
};

module.exports = { TOPICS, CLINICS };